name: CI

on:
  push:
  pull_request:

jobs:
  js:
    strategy: { matrix: { version: [18, 20, 22] } }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: lint
        run: pnpm lint
      - name: build
        run: pnpm build
      - name: test
        run: pnpm test
      - name: generate lcov coverage
        run: pnpm exec c8 --all --src dist report --reporter=text-lcov > coverage/lcov.info
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
